//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class equipment
    {
        public int id { get; set; }
        [Display(Name = "Name")]
        public string name { get; set; }
        [Display(Name = "Price")]
        public Nullable<int> price { get; set; }
        [Display(Name = "Equipment Type")]
        public Nullable<int> equiptype { get; set; }
        [Display(Name = "Purchase Date")]
        public Nullable<System.DateTime> purchdate { get; set; }
    
        public virtual category category { get; set; }
    }
}
